pool:
  vmImage: 'ubuntu-latest'

trigger:
- main

pr:
- main

variables:
- name: namespace
  value: argeu-service
- group: gcloud

steps:
- template: ./node-build.yaml
  parameters:
    nodeVersionSpec: 12.x

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Dockerfile'
    ArtifactName: 'teste'